[build]
builder = "nixpacks"
# Let Nixpacks handle Python setup automatically
# Avoiding virtual env creation that's causing file locking issues

[deploy]
startCommand = "python ./initialize.py && python ./run_ui.py --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[variables]
PORT.default = "80"
WEB_UI_PORT.default = "80"
MEMORY_DIR.default = "/app/memory"