[build]
builder = "nixpacks"
buildCommand = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[deploy]
startCommand = "python3 ./initialize.py && python3 ./run_ui.py --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[variables]
PORT.default = "80"
WEB_UI_PORT.default = "80"
MEMORY_DIR.default = "/app/memory"